server:
  port: 8555

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: hello
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: v1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 10
    disable-delta: true

management:
  endpoints:
    web:
      exposure:
        include: '*'