server:
  port: 8765

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-sentinel
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    sentinel:
      filter:
        enabled: true
      transport:
        port: 8766
        client-ip: 10.54.9.24
        dashboard: localhost:8858
      eager: true
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: testa
          uri: lb://testa
          predicates:
            - Path=/testa/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: v1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 10
    disable-delta: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com:
      alibaba: debug
    org:
      springframework: info


ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  MaxAutoRetries: 1
  httpclient:
    enabled: false
  okhttp:
    enabled: true

feign:
  sentinel:
    enabled: true